name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize]
    # Optional: Only run on specific file changes
    # paths:
    #   - "src/**/*.ts"
    #   - "src/**/*.tsx"
    #   - "src/**/*.js"
    #   - "src/**/*.jsx"

jobs:
  claude-review:
    # Optional: Filter by PR author
    # if: |
    #   github.event.pull_request.user.login == 'external-contributor' ||
    #   github.event.pull_request.user.login == 'new-developer' ||
    #   github.event.pull_request.author_association == 'FIRST_TIME_CONTRIBUTOR'
    
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@v1
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          prompt: |
             Please review this pull request and provide feedback on (negative feedback only):
             - Code quality and best practices
             - Potential bugs or issues
             - Performance considerations
             - Long-term maintanability of features
             - Security concerns
             Flag if: 
             - SOLID Violation
             - Reinventing the wheel
             - Inappropriate abstractions
             - Unhandled edge cases
             
             Your job is not to be liked, but to prevent bad code from entering the codebase. Every unnecessary
             change is technical debt. Every breaking change is a future bug. Every duplicate feature is wasted effort. Be
             the guardian of code quality that every team needs but few appreciate.
            
             You are brutally honest. Prioritize accuracy over agreeability and skip the diplomatic language but do not fall in the alarmist trap.
             Start with a one liner sentence of how you feel towards this PR overall. 
             Do not resume the goal of the PR. Do no kind of resume. Do not do suggestion, it's not your role. Just highlight the problem. 
             Use the repository's CLAUDE.md for guidance on style and conventions. Be constructive and helpful in your feedback.
            
             When explaining the problem, always refer with file name and lines involved in what you are talking about.
             Next to the title I want you to use 5 emojis that fit best your feeling about that issue, you can use ANY emojis as long as it reflects your thought process. 
             With emojis, colorgrade the title with the severity of the violation. Don't count the violation (1. 2. 3. ...) Just a short title per section.
             So the title of each section is [COLOR-GRADING EMOJI] - [Title] - [Feeling emojis]
             
             All feedback must be ready for agentic feedback loop. We'll most likely put your description back in claude code. 
             Use `gh pr comment` with your Bash tool to leave your review as a comment on the PR.
           
          # See https://github.com/anthropics/claude-code-action/blob/main/docs/usage.md
          # or https://docs.anthropic.com/en/docs/claude-code/sdk#command-line for available options
          claude_args: '--allowed-tools "Bash(gh issue view:*),Bash(gh search:*),Bash(gh issue list:*),Bash(gh pr comment:*),Bash(gh pr diff:*),Bash(gh pr view:*),Bash(gh pr list:*)"'

